name: 'Start Circle CI Release'
description: "Triggers the CircleCI pipeline"

inputs:
  # ------------------------------------------------------------------------------------
  # ENVIRONMENT SETTINGS
  CIRCLECI_KEY:
    description: "CircleCI token"
    required: true
  SW_VERSION:
    description: "The Shopware version that should be released"
    required: true
  SET_LATEST:
    description: "Whether its the latest or not"
    default: 'false'
    required: false

runs:
  using: "composite"
  steps:

    - name: Trigger CircleCI
      shell: bash
      run: | 
          cd .circleci && sh run.sh ${{ inputs.CIRCLECI_KEY }} ${{ inputs.SW_VERSION }} ${{ inputs.SET_LATEST }}
