name: Build and publish the Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version of the image to build'
        required: true
        default: 'play'
      tag:
        description: 'Which tag of the image to build'
        required: true
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.inputs.version }}
  CONTEXT_PATH: .dist/versions/${{ github.ref_name }}/${{ github.event.inputs.version }}/${{ github.event.inputs.tag }}

jobs:
  build-arm64-image:
    runs-on: custom-arm64
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Log in to the container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker buildx for cache
        uses: docker/setup-buildx-action@v3.5.0

      - name: Repository name to lowercase
        run: |
          echo "FULL_LOWERCASE_NAME=${REGISTRY}/${IMAGE_NAME@L}" >> "${GITHUB_ENV}"

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6.5.0
        with:
          platforms: linux/arm64
          outputs: type=image,name=${{ env.FULL_LOWERCASE_NAME }},push-by-digest=true,name-canonical=true,push=true
          context: ${{ env.CONTEXT_PATH }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.FULL_LOWERCASE_NAME }}:buildcache-arm64
          cache-to: type=registry,ref=${{ env.FULL_LOWERCASE_NAME }}:buildcache-arm64,mode=max

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4.3.4
        with:
          name: digests-linux-arm64
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  build-amd64-image:
    runs-on: custom-amd64
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Log in to the container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker buildx for cache
        uses: docker/setup-buildx-action@v3.5.0

      - name: Repository name to lowercase
        run: |
          echo "FULL_LOWERCASE_NAME=${REGISTRY}/${IMAGE_NAME@L}" >> "${GITHUB_ENV}"

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6.5.0
        with:
          platforms: linux/amd64
          outputs: type=image,name=${{ env.FULL_LOWERCASE_NAME }},push-by-digest=true,name-canonical=true,push=true
          context: ${{ env.CONTEXT_PATH }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.FULL_LOWERCASE_NAME }}:buildcache-amd64
          cache-to: type=registry,ref=${{ env.FULL_LOWERCASE_NAME }}:buildcache-amd64,mode=max

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4.3.4
        with:
          name: digests-linux-amd64
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-digests:
    runs-on: custom-amd64
    needs: [ build-arm64-image, build-amd64-image ]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4.1.8
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to the container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Repository name to lowercase
        run: |
          echo "FULL_LOWERCASE_NAME=${REGISTRY}/${IMAGE_NAME@L}" >> "${GITHUB_ENV}"

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create -t ${{ env.FULL_LOWERCASE_NAME }}:${{ github.event.inputs.tag }} $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.FULL_LOWERCASE_NAME }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.FULL_LOWERCASE_NAME }}:${{ github.event.inputs.tag }}
