name: Release Shopware 5.6.*

on:
  workflow_dispatch:

jobs:
  on-push:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shopware: '5.6.10'
          - shopware: '5.6.9'
          - shopware: '5.6.8'
          - shopware: '5.6.7'
          - shopware: '5.6.6'
          - shopware: '5.6.5'
          - shopware: '5.6.4'
          - shopware: '5.6.3'
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Release, Shopware ${{ matrix.shopware }}
        uses: ./.github/actions/circleci
        with:
          # -------------------------------------------
          SW_VERSION: ${{ matrix.shopware }}
          SET_LATEST: 'false'
          # -------------------------------------------
          CIRCLECI_KEY: ${{ secrets.CIRCLE_CI_TOKEN }}
          # -------------------------------------------

